title: Minimal theme
logo: /assets/img/Rahul Potghan.jpg
description: <p>My Self Rahul Potghan. I have 5+ years of exprience working in IT industry as software engineer</p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
